spring.application.name=day_5_assignment
spring.datasource.url=jdbc:postgresql://localhost:5433/files
spring.datasource.username=postgres
spring.datasource.password=Root@123
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.open-in-view=false
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect




spring.security.oauth2.resourceserver.jwt.issuer-uri=https://dev-f61fvtyov51l4g6w.us.auth0.com/
spring.security.oauth2.resourceserver.jwt.jws-algorithms=RS256
management.endpoints.web.exposure.include=health,info,metrics,loggers,env,prometheus
management.endpoint.health.show-details=always
management.endpoint.metrics.enabled=true

spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB       
spring.servlet.multipart.max-request-size=20MB    
# spring.servlet.multipart.location=/tmp            


backblaze.accessKeyId=005b4c0e9041fac0000000001
backblaze.secretKey=K005JH6PEAgs8ayzi0Q+2kNOg95QI1o
backblaze.endpoint=https://s3.us-east-005.backblazeb2.com
backblaze.region=us-east-005
backblaze.bucketName=test-mb